/// <reference types="node" />
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const SEED_PRODUCTS = [
  {
    id: 'schoolycore',
    title: 'SchoolyCore ERP',
    subtitle: 'FEATURED',
    description: 'Complete K-12 and Higher-Ed Institute Management platform with automated fee collection, exams, and parent portal.',
    shortDesc: 'Complete K-12 and Higher-Ed Institute Management platform with automated fee collection, exams, and parent portal.',
    icon: 'GraduationCap',
    gradient: 'from-blue-600 to-cyan-500',
    category: 'industry',
    categoryLabel: 'Education & Academics',
    industry: 'Education & Academics',
    badge: 'FEATURED',
    price: 'From ₹49/mo',
    priceValue: 49,
    discount: 10,
    slug: 'schoolycore-erp',
    order: 0,
    status: 'featured',
    isEnabled: true,
    aiPowered: true,
    rating: 4.9,
    reviewsCount: 1420,
    features: [
      'Student Lifecycle & Online Admissions',
      'Automated Fee Collection Gateway & Auto Receipts',
      'Exams, Grading & Custom Report Card Generator',
      'Parent & Student iOS / Android Mobile App',
    ],
  },
  {
    id: 'schoolycore-lite',
    title: 'SchoolyCore Lite',
    subtitle: 'LITE MODULE',
    description: 'Lightweight institute management system for core attendance, basic fee billing, parent alerts, and student records.',
    shortDesc: 'Lightweight institute management system for core attendance, basic fee billing, parent alerts, and student records.',
    icon: 'Building',
    gradient: 'from-emerald-600 to-teal-500',
    category: 'industry',
    categoryLabel: 'Education & Academics',
    industry: 'Education & Academics',
    badge: 'LITE MODULE',
    price: 'From ₹29/mo',
    priceValue: 29,
    discount: 0,
    slug: 'schoolycore-lite',
    order: 1,
    status: 'active',
    isEnabled: true,
    aiPowered: false,
    rating: 4.7,
    reviewsCount: 840,
    features: [
      'Core Student Roster & Contact Directory',
      'Basic Fee Receipt Generator & Payment Tracking',
      'Daily Attendance Logging & SMS Parent Alerts',
      '1-Click CSV Student Data Import / Export',
    ],
  },
  {
    id: 'hms-health',
    title: 'Dezo Care HMS',
    subtitle: 'POPULAR',
    description: 'Enterprise Hospital Management System covering OPD/IPD, Electronic Health Records, Pharmacy, and Telehealth.',
    shortDesc: 'Enterprise Hospital Management System covering OPD/IPD, Electronic Health Records, Pharmacy, and Telehealth.',
    icon: 'Cross',
    gradient: 'from-emerald-600 to-teal-500',
    category: 'industry',
    categoryLabel: 'Healthcare & Telemedicine',
    industry: 'Healthcare & Telemedicine',
    badge: 'POPULAR',
    price: 'From ₹89/mo',
    priceValue: 89,
    discount: 15,
    slug: 'dezo-care-hms',
    order: 2,
    status: 'active',
    isEnabled: true,
    aiPowered: true,
    rating: 4.8,
    reviewsCount: 890,
    features: [
      'OPD / IPD Patient Management & Bed Allocation',
      'EHR & Digital Doctor Prescriptions Engine',
      'Pharmacy & Pathology Lab Billing Integration',
      'NABH Compliance Audit Trail Logs',
    ],
  },
  {
    id: 'dezoryn-hrms',
    title: 'Dezoryn HRMS Pulse',
    subtitle: 'ENTERPRISE',
    description: 'Automated Human Resource suite for payroll processing, biometric attendance, performance tracking, and hiring.',
    shortDesc: 'Automated Human Resource suite for payroll processing, biometric attendance, performance tracking, and hiring.',
    icon: 'Users2',
    gradient: 'from-purple-600 to-indigo-500',
    category: 'erp',
    categoryLabel: 'ERP & Operations',
    industry: 'Human Resources',
    badge: 'ENTERPRISE',
    price: 'From ₹39/mo',
    priceValue: 39,
    discount: 0,
    slug: 'dezoryn-hrms-pulse',
    order: 3,
    status: 'active',
    isEnabled: true,
    aiPowered: true,
    rating: 4.9,
    reviewsCount: 2100,
    features: [
      '1-Click Multi-State Automated Payroll Run',
      'Biometric & Geo-Fenced Mobile Attendance',
      'Employee Self-Service (ESS) Leave Portal',
      'Performance Appraisals & Goal Tracking (OKRs)',
    ],
  },
  {
    id: 'inventory-pro',
    title: 'InventoryPro Matrix',
    subtitle: 'CORE',
    description: 'Multi-warehouse stock control, barcode scanner integration, automated purchase ordering, and low-stock alerts.',
    shortDesc: 'Multi-warehouse stock control, barcode scanner integration, automated purchase ordering, and low-stock alerts.',
    icon: 'Boxes',
    gradient: 'from-amber-600 to-orange-500',
    category: 'erp',
    categoryLabel: 'ERP & Operations',
    industry: 'Manufacturing & Industrial',
    badge: 'CORE',
    price: 'From ₹49/mo',
    priceValue: 49,
    discount: 0,
    slug: 'inventory-pro-matrix',
    order: 4,
    status: 'active',
    isEnabled: true,
    aiPowered: false,
    rating: 4.8,
    reviewsCount: 1340,
    features: [
      'Multi-Location Real-Time Stock Tracking',
      'Barcode & QR Scanner Hardware Integration',
      'Automated Low-Stock Vendor Purchase Orders',
      'Batch Number & Expiry Date Management',
    ],
  },
  {
    id: 'sales-ai-copilot',
    title: 'DezoAI Sales Copilot',
    subtitle: 'AI DRIVEN',
    description: 'Autonomous AI agent to score leads, generate personalized multi-channel outreach, and predict pipeline deal win rates.',
    shortDesc: 'Autonomous AI agent to score leads, generate personalized multi-channel outreach, and predict pipeline deal win rates.',
    icon: 'Zap',
    gradient: 'from-cyan-600 to-blue-500',
    category: 'ai',
    categoryLabel: 'AI Products',
    industry: 'Enterprise SaaS',
    badge: 'AI DRIVEN',
    price: 'From ₹79/mo',
    priceValue: 79,
    discount: 20,
    slug: 'dezo-ai-sales-copilot',
    order: 5,
    status: 'featured',
    isEnabled: true,
    aiPowered: true,
    rating: 4.95,
    reviewsCount: 1650,
    features: [
      'Real-Time Predictive Lead Scoring Engine',
      'Generative Cold Email & LinkedIn Pitch Drafter',
      'CRM Deal Win Probability Forecast',
      'Automated Meeting Notes & Action Items AI',
    ],
  },
  {
    id: 'dezo-crm-suite',
    title: 'Dezo CRM 360',
    subtitle: 'PIPELINE OS',
    description: 'Unified customer relationship management with drag-and-drop deal Kanban, omnichannel inbox, and quota attainment leaderboards.',
    shortDesc: 'Unified customer relationship management with drag-and-drop deal Kanban, omnichannel inbox, and quota attainment leaderboards.',
    icon: 'Layers',
    gradient: 'from-blue-600 to-cyan-500',
    category: 'crm',
    categoryLabel: 'CRM & Sales',
    industry: 'Sales & Marketing',
    badge: 'PIPELINE OS',
    price: 'From ₹29/mo',
    priceValue: 29,
    discount: 10,
    slug: 'dezo-crm-360',
    order: 6,
    status: 'active',
    isEnabled: true,
    aiPowered: true,
    rating: 4.9,
    reviewsCount: 1980,
    features: [
      'Visual Drag-and-Drop Deal Kanban Board',
      'Unified Omnichannel Customer Inbox',
      'Custom Webhooks & REST API Integrations',
      'Sales Rep Quota Attainment Leaderboards',
    ],
  },
];

async function seedProducts() {
  console.log('🌱 Seeding development marketplace products...');
  for (const prod of SEED_PRODUCTS) {
    await prisma.product.upsert({
      where: { id: prod.id },
      update: prod as any,
      create: prod as any,
    });
  }
  console.log(`✅ Seeded ${SEED_PRODUCTS.length} development products successfully.`);
}

seedProducts()
  .catch((e) => {
    console.error('❌ Error seeding products:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
